spring:
  aop:
    proxy-target-class: true
  #  application:
  #    name: ois-mock-facade
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/page?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: freddy
    password: 2frederica.99z17
    filters: stat,wall,log4j
    dbcp2:                                           # 数据库连接池配置-通过配置，让缓冲池去测试连接是否被回收，若被回收，则不继续使用
      min-idle: 5                                    # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 50                                 # 最大的连接数
      max-wait-millis: 200                         # 等待连接获取的最大超时时间
      validation-query: SELECT 1                    # SQL查询,用来验证从池中取出的连接
      test-while-idle: true                        # 检测连接是否被空闲连接回收器进行检验，若检测失败，则连接将被从池中移除
      min-evictable-idle-time-millis: 3600000      # 被逐出连接池的时间-连接池中连接，在时间段内【(1000*60*60)毫秒】一直空闲

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
mybatis:
  #  config-location: classpath:mybatis.xml
  mapper-locations: classpath*:mapper/*.xml

#spring.datasource.url=jdbc:mysql://localhost:3306/studyjdbc
#spring.datasource.username=root
#spring.datasource.password=123
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#spring.jpa.properties.hibernate.hbm2ddl.auto=update

logging:
  file: "logs/mybatis-code-helper-file.log"
  level:
    root: INFO
    cc.dt: DEBUG